image: docker:19.03

services:
  - docker:19.03-dind

stages:
  - build_and_push
  - deploy

variables:
  DOCKERHUB_USERNAME: licalv
  DOCKERHUB_TOKEN: dckr_pat_CHIGoNqOBzNOO0RSrPGSaKCagoo
  RENDER_API_KEY: P4KGtUpQ_gw

build_and_push:
  stage: build_and_push
  tags:
    - docker
  script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
    - echo "Logging in..."
    - docker build --platform=linux/amd64 -t api -f ./API/Dockerfile ./API
    - docker tag api $DOCKERHUB_USERNAME/world-builder-api
    - docker push $DOCKERHUB_USERNAME/world-builder-api
    - echo "Pushing to Docker Hub..."

deploy_to_render:
  stage: deploy
  tags:
    - shell
  script:
    - curl https://api.render.com/deploy/srv-ck0i3fm3ktkc73edlj8g?key=$RENDER_API_KEY
    - echo "Sent deploy request to Render."
