stages:
  - build

build-docker:
  stage: build
  tags: 
    - shell
  script:
    - mvn --version
    - cd ./API
    - /usr/pkg/bin/mvn clean install
    - cd ..
    - echo "This is a shell script command"
    - ./deploy.sh
