stages:
  - build_and_push
  - deploy

build_and_push:
  stage: build_and_push
  tags:
    - shell
  script:
    - docker login -u licalv -p $DOCKER_KEY
    - echo "Logging in..."
    - docker build --platform=linux/amd64 -t api -f ./API/Dockerfile ./API
    - docker tag api licalv/world-builder-api
    - docker push licalv/world-builder-api
    - echo "Pushing to Docker Hub..."

deploy_to_render:
  stage: deploy
  tags:
    - shell
  script:
    - curl https://api.render.com/deploy/srv-ck0i3fm3ktkc73edlj8g?key=P4KGtUpQ_gw
    - echo "Sent deploy request to Render."
