variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

image: maven:latest

stages:
  - build

build-docker:
  stage: build
  tags: 
    - shell
  services:
    - docker:dind
  script:
    - mvn --version
    - echo "This is a shell script command"
    - ./deploy.sh
