import { createContext } from "react";

export const WorldDataContext = createContext({
    worldData: [],
    loading: false,
    history: [],
    host: false,
    gameId: "",
    clientRef: null,
    currentPlayersInGame: 0,
    caveCords: [],
    buildingCords: [],
    frameValue: true,
    setWorldData: () => {},
    setAuthentication: () => {},
    setHistory: () => {},
    setHost: ()=>{},
    setGameId: ()=>{},
    setClientRef: ()=>{},
    sendMessage: ()=>{},
    setCurrentPlayersInGame: ()=>{},
    setCaveCords: ()=>{},
    setBuildingCords: ()=>{},
    setWorldData: () => { },
    setAuthentication: () => { },
    setOpacityRoofValue: () => { },
    setHistory: () => { },
    setOpacityCaveValue: () => { },
    setHost: () => { },
    setGameId: () => { },
    setClientRef: () => { },
    sendMessage: () => { },
    setCurrentPlayersInGame: () => { },
    setFrameState: () => { }
});